### PR TITLE
update per David Kilgore

### PR DESCRIPTION
**Pull request by catlook**

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 74 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-9da61e67e/docs/style-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 76 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-4dfd5b61b/docs/style-guide/). valid for 14 days

**Pull request merged**
